markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "space_after_headers", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "smart"]
highlighter: pygments
permalink: posts/:title
paginate: 6
paginate_path: "posts/page:num"
navigation:
    - text: projects
      url: /
    - text: photo essays
      url: /photo_essays/
    - text: posts
      url: /posts/
    - text: about
      url: /about/
name: rpk
email: kostis.rpk@gmail
url: http://rpk.io
description: "Contemporary urban and sub-urban landscapes which emit the feeling of loneliness, abandonment and curiosity. Film photography - Software development - Ruby - Ruby on Rails"
google_plus: https://plus.google.com/106674914836183072429
twitter: rpk0_
github: rpk0
flickr: rp0
gravatar_url: https://s.gravatar.com/avatar/8bc43bee9040db6434f0842501858358?s=80
